// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// qubic
int qubic(const CharacterVector& str);
RcppExport SEXP _IRISFGM_qubic(SEXP strSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const CharacterVector& >::type str(strSEXP);
    rcpp_result_gen = Rcpp::wrap(qubic(str));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_IRISFGM_qubic", (DL_FUNC) &_IRISFGM_qubic, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_IRISFGM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
