# Generated by using Rcpp::compileAttributes() -> do not edit by hand Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @backref src/rcpp_irisfgm.cpp
.main <- function(str) {
    .Call("_IRISFGM_qubic", PACKAGE = "IRISFGM", str)
}

